### ISSUE TITLE
Create new TOFU image ads

### ISSUE THREAD

**Issue by gabrielzamp** [gabrielzamp/gz-hostinger#12]
Image Briefing:

![image](https://user-images.githubusercontent.com/63654106/89288973-de9da580-d62c-11ea-95cc-38a586f9e783.png)

Images Sizes:

- [ ] 1200 x 628 pixels (feed horizontal)
- [ ] 1080x1920 Pixels (Stories)
- [ ] 1080 x 1080 pixels (feed square)

Argument:

- Europe's Fastest Growing companies 2020 (https://www.ft.com/content/691390ca-53d9-11ea-90ad-25e377c0ee1f)

Variations:

- [ ] Br Agent
- [ ] BR Team
- [ ] LT Team

**Comment by monicaandrade** [comment]
Br Agent
![Ads-1hiring-Q3-2020-horizontal-agent1](https://user-images.githubusercontent.com/33291732/89582779-9db1b680-d80f-11ea-8c4a-3673292db928.gif)
![Ads-1hiring-Q3-2020-quadrado-agent1](https://user-images.githubusercontent.com/33291732/89582783-9e4a4d00-d80f-11ea-9da4-c378746fb4b7.gif)
![Ads-1hiring-Q3-2020-vertical-agent1](https://user-images.githubusercontent.com/33291732/89582784-9ee2e380-d80f-11ea-8ad7-de703160347b.gif)

**Comment by monicaandrade** [comment]
BR Team

![Ads-2hiring-Q3-2020-horizontal-timebr](https://user-images.githubusercontent.com/33291732/89583008-f7b27c00-d80f-11ea-80e5-b436e3a5c8db.gif)
![Ads-2hiring-Q3-2020-quadrado-timebr](https://user-images.githubusercontent.com/33291732/89583013-f8e3a900-d80f-11ea-916c-356a60972394.gif)
![Ads-2hiring-Q3-2020-vertical-timebr](https://user-images.githubusercontent.com/33291732/89583015-f97c3f80-d80f-11ea-824e-1cc0a90abe8a.gif)

**Comment by monicaandrade** [comment]
LT Team model 1

![Ads-3hiring-Q3-2020-quadrado-timelt1](https://user-images.githubusercontent.com/33291732/89583060-0e58d300-d810-11ea-824e-0e4417bb0ae3.gif)
![Ads-3hiring-Q3-2020-vertical-timelt](https://user-images.githubusercontent.com/33291732/89583064-0ef16980-d810-11ea-8730-41c64291f33a.gif)
![Ads-3hiring-Q3-2020-horizontal-timelt1](https://user-images.githubusercontent.com/33291732/89583066-10229680-d810-11ea-84b4-3f1af9490dfc.gif)

**Comment by monicaandrade** [comment]
LT Team model 2

![Ads-3hiring-Q3-2020-quadrado-timelt](https://user-images.githubusercontent.com/33291732/89583104-216ba300-d810-11ea-9d7f-b2c1c71dfb8f.gif)
![Ads-3hiring-Q3-2020-horizontal-timelt](https://user-images.githubusercontent.com/33291732/89583108-229cd000-d810-11ea-91ee-64fdd72c4d7e.gif)

**Comment by monicaandrade** [comment]
All of them was tested on Text overlay and Facebook Grid Tool and has passed as OK. Sometimes the pack was desconsidered.

Open AI document was send by e-mail (gzampierimkt@gmail.com) because Github don't allow this file type.

**Comment by gabrielzamp** [comment]
@monicaandrade 

Text Fixing:

Uma das empresas de tecnologia que cresce mais rápido na Europa em 2020

**Comment by monicaandrade** [comment]
Text fixed and already updated on the comments above.
